Repository tabarra/txAdmin, pull requests merged in 2024-02, with the labels that each got.

#912 Update settings.ejs
  web/main/settings.ejs
Labels: bug

#904 Add missing weapons from DLCs to txAdmin kill internal kill logs
  resource/cl_logger.lua
Labels: enhancement

#901 Unnecessary wording in the Japanese translation string has been removed
  locale/ja.json
Labels: translation

#906 locale: fixed cs typo
  locale/cs.json
Labels: translation

#851 fix(nui/PlayerModel): require OneSync for bring and goto
  locale/en.json
  nui/src/components/PlayerModal/Tabs/DialogActionView.tsx
Labels: bug
