Repository tabarra/txAdmin, pull requests merged in 2025-02, with the labels that each got.

#1030 Modify translate Vietnameses
  locale/vi.json
Labels: translation

#1028 Update permissions.md
  docs/permissions.md
Labels: docs

#1008 fix(panel): don't focus bg color on select dropdownmenu in desktopnavbar
  panel/src/components/ui/navigation-menu.tsx
Labels: ui
